#!python
# https://www.hackerrank.com/challenges/bon-appetit
import sys

class Dinner:
    
    def __init__(self, x, y, z):
        self.index_of_item_anna_skips = x[1]
        self.items_eaten = y
        self.amount_charged = z[0]
    
    def remove_annas_item(self):
        self.items_eaten.remove(self.items_eaten[self.index_of_item_anna_skips])
        return self.items_eaten

def bon_appetit_calculator(Dinner):
    items_anna_ate = Dinner.remove_annas_item()
    anna_pays = sum(items_anna_ate) / 2
    anna_is_owed = Dinner.amount_charged - anna_pays
    if anna_is_owed == 0:
        return "Bon Appetit"
    else:
        return int(anna_is_owed)
    

def test_bon_appetit_calculator():
    sample_input_1 = Dinner([4, 1], [3, 10, 2, 9], [12])
    result = bon_appetit_calculator(sample_input_1)
    print("%s %s" % (5 == result, result))
    sample_input_2 = Dinner([4, 1], [3, 10, 2, 9], [7])
    result_2 = bon_appetit_calculator(sample_input_2)
    print("%s %s" % ("Bon Appetit" == result_2, result_2))

    
x = list(map(int, input().split()))
y = list(map(int, input().split()))
z = list(map(int, input().split()))

dinner = Dinner(x, y, z)

#print(bon_appetit_calculator(dinner))
test_bon_appetit_calculator()
